apiVersion: v1
kind: Service
metadata:
  name: kimi-k3-pp2
  labels:
    app.kubernetes.io/name: kimi-k3-pp2
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: kimi-k3-pp2
    app.kubernetes.io/component: leader
  type: ClusterIP
