apiVersion: v1
kind: Service
metadata:
  name: kimi-k3-vllm-h200-pp2-tp8
  labels:
    app.kubernetes.io/name: kimi-k3-vllm-h200-pp2-tp8
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: kimi-k3-vllm-h200-pp2-tp8
    role: leader
  type: ClusterIP
