apiVersion: v1
kind: Service
metadata:
  name: kimi-k3-pp2-api
  labels:
    app.kubernetes.io/name: kimi-k3-pp2
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: kimi-k3-pp2
    leaderworkerset.sigs.k8s.io/worker-index: "0"
  type: ClusterIP
